/**
 * Per-city operational layer — how Sanat Dynamo *actually delivers* in each
 * metro. Sits alongside `cities.ts` (commercial copy), `city-extras.ts`
 * (operational hidden gem + global peers), and `city-identity.ts`
 * (heritage + visual identity).
 *
 * Drives the "How we operate in {city}" section on the city page. The
 * content here is hand-written, not templated — every entry is rooted in
 * specific neighborhoods, languages, stacks, and cadences we genuinely
 * apply in that metro. Without this specificity Google demotes it as
 * generic "we serve {city}" boilerplate.
 *
 * Important SEO outcome: the on-page anchors generated by section IDs
 * become long-tail-rankable URLs of their own (e.g. `#engagement-mumbai`,
 * `#cadence-bengaluru`).
 */

export interface EngagementPhase {
  /** Phase label — e.g. "Discovery week" */
  name: string;
  /** Duration phrase — e.g. "Week 1 · 5 days · paid" */
  duration: string;
  /** 1-line phase mission */
  mission: string;
  /** 2-4 artefacts that come out of this phase */
  artefacts: string[];
  /** City-specific note — what this phase looks like in this metro */
  cityNote: string;
}

export interface StackLayer {
  /** Layer label — "Communication", "Payments", "CRM", etc. */
  category: string;
  /** Tools we default to in this city */
  tools: string[];
  /** Why this stack for this city — 1 line */
  cityNote: string;
}

export interface CadenceBeat {
  /** Day label — "Mon", "Tue", "Fri" */
  day: string;
  /** What happens — "Async standup" / "Friday Loom demo" */
  ritual: string;
  /** Channel — "WhatsApp", "Slack", "Loom" */
  channel: string;
}

export interface ProofPoint {
  metric: string;
  label: string;
}

export interface CityOrganization {
  slug: string;
  /** Presence model — drives the orbit visualization animation */
  presenceModel: "remote-first" | "hybrid-onsite" | "site-visit";
  /** 1-line operating-model pitch — surfaces in the sticky left rail */
  presenceTagline: string;
  /** Specific neighborhood / GIDC / cluster names we visit */
  onSiteCadence: string;
  /** Engagement-lead role label — not a name (so it doesn't go stale) */
  leadRole: string;
  /** Languages we operate in here */
  languages: string[];
  /** Hours of overlap — IST default, plus US/EU overlap where relevant */
  hours: string;
  /** 4 phases — discovery → design → build → compound */
  engagement: EngagementPhase[];
  /** Tooling we default to in this metro — 4-6 layers */
  stack: StackLayer[];
  /** Weekly communication ritual */
  cadence: CadenceBeat[];
  /** 4 quantified proofs of operational fit in this city */
  proofPoints: ProofPoint[];
  /** Commercial / billing notes specific to this city */
  commercialNotes: string[];
}

/* -------------------------------------------------------------------------- */
/*                                   DATA                                     */
/* -------------------------------------------------------------------------- */

const COMMON_PHASES = (citySpecific: Record<number, string>): EngagementPhase[] => [
  {
    name: "Discovery week",
    duration: "Week 1 · 5 working days · paid",
    mission:
      "Map the funnel end-to-end. Identify the top 3 revenue leaks. Lock the build scope on a fixed price.",
    artefacts: [
      "12–20 page written revenue audit",
      "Top 3 leaks ranked by impact",
      "Fixed-price phased build proposal",
    ],
    cityNote: citySpecific[0] ?? "",
  },
  {
    name: "Design + scope lock",
    duration: "Weeks 2–3",
    mission:
      "Wireframe + content architecture + integration map. Founder signs off before any code is written.",
    artefacts: [
      "Wireframes + flows (Figma)",
      "Tech architecture + integration map",
      "Migration plan for legacy systems",
    ],
    cityNote: citySpecific[1] ?? "",
  },
  {
    name: "Build + go-live",
    duration: "Weeks 4–14",
    mission:
      "Ship in 2-week sprints. Friday demo every week. Final 2 weeks are go-live + parallel-run.",
    artefacts: [
      "Phased deliverables on a public timeline",
      "Weekly Friday Loom demo + changelog",
      "Final go-live + 2-week stabilisation",
    ],
    cityNote: citySpecific[2] ?? "",
  },
  {
    name: "Compound retainer",
    duration: "Month 4 onwards · monthly",
    mission:
      "Tune conversion, ship new flows, monthly metrics review. The build stops being a project and becomes an engine.",
    artefacts: [
      "Monthly conversion tuning",
      "Quarterly growth review",
      "Direct Slack with the build team",
    ],
    cityNote: citySpecific[3] ?? "",
  },
];

export const CITY_ORGANIZATION: Record<string, CityOrganization> = {
  /* ============================== MUMBAI ============================== */
  mumbai: {
    slug: "mumbai",
    presenceModel: "hybrid-onsite",
    presenceTagline:
      "Remote-first delivery with monthly Bandra–Andheri–BKC kickoffs and on-call site visits during major launches.",
    onSiteCadence:
      "Monthly visits to BKC / Lower Parel for BFSI clients · weekly Bandra–Andheri syncs during D2C launches",
    leadRole: "Engagement lead",
    languages: ["English", "Hindi", "Marathi"],
    hours: "Mon–Sat · 10–19 IST · 1–3h US-ET overlap for diaspora launches",
    engagement: COMMON_PHASES({
      0: "BFSI / NBFC clients sign DPDP-aligned DPAs in week 1. D2C clients on Shopify Plus get Razorpay + WATI provisioning kicked off in parallel.",
      1: "Bandra–Andheri D2C migrations are scoped against Klaviyo + WATI dual-lifecycle. BKC NBFC funnels are scoped against compliance posture (KYC + DPDP).",
      2: "WhatsApp 90-second cart-recovery goes live in week 6 — the rest of the build compounds on top of that lever.",
      3: "Mumbai retainers run heavy on lifecycle tuning — most CAC compression we ship in the first 90 days post go-live.",
    }),
    stack: [
      {
        category: "Communication",
        tools: ["WATI", "Gupshup", "WhatsApp Business API"],
        cityNote: "WhatsApp is the actual CRM for Andheri D2C — primary channel from day 1.",
      },
      {
        category: "Payments",
        tools: ["Razorpay", "Cashfree", "Stripe (NRI flows)"],
        cityNote: "Razorpay default for INR + GST. Stripe for Bandra brands selling US/UK.",
      },
      {
        category: "CRM + lifecycle",
        tools: ["Klaviyo", "MoEngage", "WATI flows"],
        cityNote: "Email + WhatsApp dual-channel. Never replace WhatsApp with email.",
      },
      {
        category: "Compliance",
        tools: ["DPDP Act 2023 DPA", "KYC for NBFC", "PCI-aware checkout"],
        cityNote: "BKC NBFC engagements close compliance posture inside week 1.",
      },
      {
        category: "Analytics",
        tools: ["GA4", "Mixpanel", "Razorpay events"],
        cityNote: "Funnel attribution from cart-create → cart-abandon → recovery.",
      },
    ],
    cadence: [
      { day: "Mon", ritual: "Async WhatsApp standup", channel: "WhatsApp" },
      { day: "Tue", ritual: "Build sprint", channel: "Slack" },
      { day: "Wed", ritual: "Mid-week unblock check", channel: "WhatsApp" },
      { day: "Thu", ritual: "QA + staging review", channel: "Loom" },
      { day: "Fri", ritual: "Friday Loom demo + changelog", channel: "Loom + Slack" },
      { day: "Sat", ritual: "On-call only", channel: "WhatsApp" },
    ],
    proofPoints: [
      { metric: "12+", label: "Mumbai engagements live" },
      { metric: "<45 days", label: "Time-to-first revenue lift" },
      { metric: "₹15Cr+", label: "Revenue impacted" },
      { metric: "<48h", label: "DPA signoff for NBFC" },
    ],
    commercialNotes: [
      "INR with GST · TDS under 194J supported",
      "Discovery week ₹2.5L–₹4L · build fixed-price",
      "Monthly retainers ₹40K–₹1.5L depending on volume",
    ],
  },

  /* ============================== DELHI ================================ */
  delhi: {
    slug: "delhi",
    presenceModel: "hybrid-onsite",
    presenceTagline:
      "Sub-5-minute routing requires presence — fortnightly Gurugram + Noida site-visit days during builder launches.",
    onSiteCadence:
      "Fortnightly Gurugram (Cyber Hub / Golf Course Road) + Noida (Sector 18 / Sector 150) days during launches",
    leadRole: "NCR engagement lead",
    languages: ["English", "Hindi", "Punjabi"],
    hours: "Mon–Sat · 10–19 IST · weekend coverage during builder launch windows",
    engagement: COMMON_PHASES({
      0: "RERA project audit for builders in week 1. Edtech clients get UPSC/NEET locality keyword research in parallel.",
      1: "Lead-routing architecture scoped first — sub-5-minute SLA is non-negotiable. CRM (Sell.do / LeadSquared / custom) decision in week 2.",
      2: "Lead routing + WATI fallback ships first (week 4–6). Project microsites + RERA pages ship next. Local SEO content compounds month 3+.",
      3: "Monthly conversion tuning weighted toward channel-partner attribution clarity and cost-per-qualified-lead reduction.",
    }),
    stack: [
      {
        category: "Lead routing",
        tools: ["Custom CRM", "WATI fallback", "Calendly site-visit booking"],
        cityNote: "Sub-5-minute SLA enforced at the system level — auto-reroute on no-pickup.",
      },
      {
        category: "Portal integration",
        tools: ["99acres API", "MagicBricks", "Housing.com", "Sulekha"],
        cityNote: "Unified inbox over all 4 portals + Meta Lead Ads + your forms.",
      },
      {
        category: "Compliance",
        tools: ["RERA disclosures", "DPDP Act 2023", "Schema markup for RERA"],
        cityNote: "RERA registration in JSON-LD on every project page.",
      },
      {
        category: "EdTech payments",
        tools: ["Razorpay", "Cashfree", "Bajaj EMI"],
        cityNote: "Coaching institute payment + EMI flows for parent-student dual UX.",
      },
      {
        category: "Channel-partner",
        tools: ["Sub-account architecture", "Commission accrual", "Lead-claim ledger"],
        cityNote: "Scales from 50-broker boutique to 500-broker network.",
      },
    ],
    cadence: [
      { day: "Mon", ritual: "Lead-flow standup", channel: "WhatsApp" },
      { day: "Tue", ritual: "Build sprint", channel: "Slack" },
      { day: "Wed", ritual: "SLA dashboard review", channel: "Slack" },
      { day: "Thu", ritual: "Site-visit calendar audit", channel: "Loom" },
      { day: "Fri", ritual: "Friday Loom demo", channel: "Loom + Slack" },
      { day: "Sat", ritual: "Launch-day support", channel: "WhatsApp" },
      { day: "Sun", ritual: "Builder weekend coverage", channel: "WhatsApp" },
    ],
    proofPoints: [
      { metric: "8+", label: "NCR builder funnels live" },
      { metric: "<5 min", label: "Lead-to-callback SLA" },
      { metric: "3.2x", label: "Site-visit conversion lift" },
      { metric: "₹4.1Cr", label: "Closed inventory in Q1 (sample)" },
    ],
    commercialNotes: [
      "INR + GST · TDS 194J supported",
      "Discovery week ₹2L–₹3.5L for NCR scope",
      "Lead-routing module ships in 4–6 weeks · CRM build 10–14 weeks",
    ],
  },

  /* ============================== BENGALURU ============================ */
  bengaluru: {
    slug: "bengaluru",
    presenceModel: "remote-first",
    presenceTagline:
      "Remote-first delivery overlapping US-PT hours for global SaaS. Quarterly Koramangala / HSR Layout in-person syncs.",
    onSiteCadence:
      "Quarterly Koramangala / Indiranagar / HSR Layout founder syncs · async-default for engineering buyers",
    leadRole: "SaaS engagement lead",
    languages: ["English", "Kannada", "Hindi", "Tamil"],
    hours: "Mon–Fri · 10–19 IST · 3–5h US-PT overlap for global SaaS clients",
    engagement: COMMON_PHASES({
      0: "Programmatic SEO audit + comparison-page gap analysis vs G2/Capterra in week 1.",
      1: "Pricing page architecture + /docs treatment + SOC2/GDPR posture scoped before any code is written.",
      2: "Marketing site rebuild ships first (6–10 weeks). Programmatic SEO module phases in next (4–6 weeks layered on top).",
      3: "Monthly conversion tuning weighted toward demo-to-close ratio and US/EU enterprise pipeline opens.",
    }),
    stack: [
      {
        category: "Marketing site",
        tools: ["Next.js", "MDX docs", "Live product screenshots"],
        cityNote: "Engineering-honest copy. No 'transform your business' filler.",
      },
      {
        category: "Payments + checkout",
        tools: ["Stripe", "Razorpay (INR fallback)", "Geo-aware pricing"],
        cityNote: "USD-default for US visitors, INR for India, EUR for EU.",
      },
      {
        category: "Compliance",
        tools: ["GDPR cookie consent", "DPA template", "SOC2-ready hosting"],
        cityNote: "Vendor-questionnaire-ready trust page — under 50 pages.",
      },
      {
        category: "Programmatic SEO",
        tools: ["Hand-edited templates", "Comparison vs competitor", "Integration landing pages"],
        cityNote: "30–80 hand-edited pages — Helpful-Content-update safe.",
      },
      {
        category: "Analytics",
        tools: ["GA4", "Mixpanel", "PostHog"],
        cityNote: "Funnel: hero → pricing → docs → demo. Track all 4.",
      },
    ],
    cadence: [
      { day: "Mon", ritual: "Sprint kickoff", channel: "Slack" },
      { day: "Tue", ritual: "Async build", channel: "Slack" },
      { day: "Wed", ritual: "Architecture review", channel: "Slack threads" },
      { day: "Thu", ritual: "QA + staging", channel: "Loom" },
      { day: "Fri", ritual: "Friday Loom demo + US sync", channel: "Loom + Zoom" },
    ],
    proofPoints: [
      { metric: "20+", label: "Bengaluru SaaS engagements" },
      { metric: "+280%", label: "Organic demos (90-day average)" },
      { metric: "+41%", label: "Demo-to-close on rebuilt funnels" },
      { metric: "₹22Cr+", label: "Pipeline impacted" },
    ],
    commercialNotes: [
      "USD MSAs supported · DPAs in 48h",
      "Discovery week ₹2.5L–₹5L (or USD equivalent)",
      "Monthly retainers ₹50K–₹2L depending on programmatic SEO scope",
    ],
  },

  /* ============================== PUNE ================================= */
  pune: {
    slug: "pune",
    presenceModel: "site-visit",
    presenceTagline:
      "Manufacturing engagements run on weekly Chakan + Pimpri-Chinchwad shop-floor visits during the build window.",
    onSiteCadence:
      "Weekly Chakan / Pimpri-Chinchwad shop-floor visits · monthly Hinjewadi / Kharadi syncs for IT-services clients",
    leadRole: "Manufacturing engagement lead",
    languages: ["English", "Hindi", "Marathi"],
    hours: "Mon–Sat · 10–19 IST · on-call during go-live week",
    engagement: COMMON_PHASES({
      0: "Tally / Marg / SAP B1 export schema audit on the shop floor in week 1. CA introduction for parallel-run sign-off.",
      1: "BOM, routing, costing, and dispatch flow modelled against your actual shop-floor reality — not generic ERP defaults.",
      2: "Phase 1 (catalog + dealer login + order placement) ships first in 6–10 weeks. Phase 2 (full ERP + GST + WhatsApp) layers on next.",
      3: "Monthly retainer focused on dealer adoption + shop-floor mobile app uptake. Founder gets daily P&L on phone.",
    }),
    stack: [
      {
        category: "ERP integration",
        tools: ["Tally Prime / ERP 9", "Marg ERP", "BUSY", "SAP Business One"],
        cityNote: "Live API for Marg/BUSY · scheduled export for Tally Silver/Gold.",
      },
      {
        category: "Dealer portal",
        tools: ["Role-based logins", "Stock + price view", "Order placement"],
        cityNote: "Dealer self-serve cuts rep phone-time 60% in 90 days.",
      },
      {
        category: "GST + e-invoicing",
        tools: ["NIC IRP API", "E-way bill auto-gen", "GSTR-1 / GSTR-3B export"],
        cityNote: "IRN at finalisation, e-way bill at dispatch — auto-retried on outage.",
      },
      {
        category: "Communication",
        tools: ["WhatsApp Business API", "Order-status broadcasts"],
        cityNote: "Dealer order status auto-pinged in Marathi/Hindi.",
      },
      {
        category: "Shop-floor mobile",
        tools: ["Offline-first PWA", "Production logging", "Material issue + rejection capture"],
        cityNote: "Works on patchy 2G/3G in factory back-end.",
      },
    ],
    cadence: [
      { day: "Mon", ritual: "Shop-floor site visit (Chakan)", channel: "On-site" },
      { day: "Tue", ritual: "Build sprint", channel: "Slack + WhatsApp" },
      { day: "Wed", ritual: "Dealer feedback round", channel: "WhatsApp" },
      { day: "Thu", ritual: "QA + integration", channel: "Loom" },
      { day: "Fri", ritual: "Friday demo + CA reconciliation review", channel: "Loom + Email" },
      { day: "Sat", ritual: "On-site go-live support", channel: "On-site" },
    ],
    proofPoints: [
      { metric: "9+", label: "Pune manufacturer ERPs live" },
      { metric: "−42%", label: "Quote-to-dispatch time" },
      { metric: "18 hrs/wk", label: "Rep time recovered" },
      { metric: "60–90 days", label: "Tally parallel-run before cut-over" },
    ],
    commercialNotes: [
      "INR + GST · TDS 194J supported",
      "Discovery week ₹3L–₹5L (factory-visit included)",
      "ERP build fixed-price · ongoing ops retainer ₹60K–₹1.8L/month",
    ],
  },

  /* ============================== CHENNAI ============================== */
  chennai: {
    slug: "chennai",
    presenceModel: "hybrid-onsite",
    presenceTagline:
      "Tamil-first delivery — bilingual content team operating from Chennai with quarterly OMR / Anna Nagar syncs.",
    onSiteCadence:
      "Quarterly OMR / Anna Nagar / Velachery syncs · monthly Sriperumbudur visits for auto-component clients",
    leadRole: "Tamil-region engagement lead",
    languages: ["Tamil", "English", "Telugu"],
    hours: "Mon–Sat · 10–19 IST · weekend appointment-cover for healthcare clients",
    engagement: COMMON_PHASES({
      0: "Bilingual keyword audit (Tamil + English) in week 1. Locality-page gap analysis for Anna Nagar / OMR / Velachery / Adyar.",
      1: "Hreflang architecture + Tamil schema + GBP-Tamil naming scoped before any code.",
      2: "Per-locality bilingual landing pages ship first (4–6 weeks). EMR / booking / review automation for healthcare layers next.",
      3: "Monthly content compounding — new locality + intent pages every cycle.",
    }),
    stack: [
      {
        category: "Bilingual content",
        tools: ["Tamil + English hreflang", "Tamil schema markup", "GBP Tamil-first"],
        cityNote: "Native Tamil writing — never machine-translated bottom-of-funnel pages.",
      },
      {
        category: "Healthcare booking",
        tools: ["WATI booking", "Auto reminders 24/4/1h", "Patient EMR (3-tap)"],
        cityNote: "Bilingual WhatsApp confirmations — Tamil first, English fallback.",
      },
      {
        category: "Auto-component portals",
        tools: ["Dealer login", "EDI / CSV export", "Tata / Hyundai-spec integration"],
        cityNote: "Sriperumbudur tier-1 suppliers need EDI compliance for OEM contracts.",
      },
      {
        category: "Reviews + retention",
        tools: ["Google review automation", "Tamil-language recall flows", "GBP posts"],
        cityNote: "5-10x review velocity from a Tamil-language ask vs English.",
      },
      {
        category: "Compliance",
        tools: ["DPDP Act 2023", "Health-data handling", "TN-state-specific"],
        cityNote: "Healthcare clients get scoped data-handling + audit log day 1.",
      },
    ],
    cadence: [
      { day: "Mon", ritual: "Bilingual content brief", channel: "Slack" },
      { day: "Tue", ritual: "Build sprint", channel: "Slack" },
      { day: "Wed", ritual: "Tamil QA pass", channel: "Loom" },
      { day: "Thu", ritual: "Healthcare booking review", channel: "WhatsApp" },
      { day: "Fri", ritual: "Friday Loom demo (bilingual)", channel: "Loom" },
      { day: "Sat", ritual: "Weekend appointment cover", channel: "WhatsApp" },
    ],
    proofPoints: [
      { metric: "+62%", label: "Organic appointments (90-day)" },
      { metric: "−25%", label: "No-show rate" },
      { metric: "5–10x", label: "Review velocity (Tamil-first)" },
      { metric: "4 weeks", label: "Booking + EMR live" },
    ],
    commercialNotes: [
      "INR + GST · TDS 194J supported",
      "Discovery week ₹2L–₹3.5L · build fixed-price",
      "Monthly retainers ₹40K–₹1.2L · bilingual content add-on ₹25K/mo",
    ],
  },

  /* ============================== HYDERABAD ============================ */
  hyderabad: {
    slug: "hyderabad",
    presenceModel: "hybrid-onsite",
    presenceTagline:
      "Pharma compliance posture from day 1 · monthly HITEC City + Genome Valley site-visit days.",
    onSiteCadence:
      "Monthly Genome Valley + HITEC City / Gachibowli syncs · quarterly Charminar-area trade visits",
    leadRole: "Regulated-industries lead",
    languages: ["English", "Telugu", "Hindi", "Urdu"],
    hours: "Mon–Sat · 10–19 IST · 2–4h US-ET overlap for export pharma clients",
    engagement: COMMON_PHASES({
      0: "DMF / GMP / CDSCO compliance-page audit in week 1. Multilingual datasheet inventory for export markets.",
      1: "/quality + /compliance site architecture + schema layer scoped before any product page.",
      2: "Compliance pages ship first (3–5 weeks). Product datasheets + procurement-facing inquiry routing layers next.",
      3: "Monthly retainer weighted toward new molecule pages + regulatory update logging.",
    }),
    stack: [
      {
        category: "Compliance + quality",
        tools: ["CDSCO / DMF / GMP schema", "ISO certificate display", "USFDA / EMA / MHRA logs"],
        cityNote: "Every audit observation + corrective action surfaced — transparency wins RFQs.",
      },
      {
        category: "Procurement routing",
        tools: ["Buyer-type capture (hospital / distributor / CDMO)", "RFQ owner routing", "Inquiry forms"],
        cityNote: "Different RFQ owner for each buyer type — no inbox chaos.",
      },
      {
        category: "Multilingual datasheets",
        tools: ["@inLanguage schema", "EU + JP + ES + DE versions", "PDF + HTML"],
        cityNote: "Schema-tagged in 4–6 languages for the markets you actually sell to.",
      },
      {
        category: "Saas / IT corridor",
        tools: ["Stripe + Razorpay", "GDPR + DPDP", "Multi-currency"],
        cityNote: "HITEC City SaaS tooling overlaps with Bengaluru playbook.",
      },
      {
        category: "Defence-grade",
        tools: ["Air-gapped review pipeline", "On-prem hosting option", "DRDL-aligned"],
        cityNote: "Available for DRDL / RCI / Tata Aerospace adjacent engagements.",
      },
    ],
    cadence: [
      { day: "Mon", ritual: "Compliance review", channel: "Slack" },
      { day: "Tue", ritual: "Build sprint", channel: "Slack" },
      { day: "Wed", ritual: "Regulatory log update", channel: "Email" },
      { day: "Thu", ritual: "Datasheet QA (multilingual)", channel: "Loom" },
      { day: "Fri", ritual: "Friday Loom demo", channel: "Loom" },
    ],
    proofPoints: [
      { metric: "+220%", label: "RFQ inbound volume (6 months)" },
      { metric: "3+", label: "New CDMO partnerships sourced organically" },
      { metric: "8–14 weeks", label: "Pharma site rebuild timeline" },
      { metric: "Month 3", label: "First measurable RFQ uplift" },
    ],
    commercialNotes: [
      "INR + GST · USD MSAs for export-pharma clients",
      "Discovery week ₹3L–₹5L (regulatory scoping included)",
      "Build fixed-price · ongoing ₹60K–₹1.5L/month",
    ],
  },

  /* ============================== KOLKATA ============================== */
  kolkata: {
    slug: "kolkata",
    presenceModel: "site-visit",
    presenceTagline:
      "Bengali-language ops desk · bi-weekly BBD Bagh / Park Street trader-floor visits during the build window.",
    onSiteCadence:
      "Bi-weekly BBD Bagh / Park Street / Burrabazar trader visits · quarterly Sector V IT corridor syncs",
    leadRole: "Bengali-region engagement lead",
    languages: ["Bengali", "Hindi", "English"],
    hours: "Mon–Sat · 10–19 IST · evening callback shifts for legacy commerce clients",
    engagement: COMMON_PHASES({
      0: "Trader-floor walkthrough in week 1 — buyer pattern observation matters here. Callback-now CTA architecture scoped.",
      1: "Click-to-call + WhatsApp opt-in design over email forms — primary conversion path.",
      2: "Callback-now funnel + skill-based routing ship first (3–4 weeks). Bilingual confirmation flows + retention layer next.",
      3: "Monthly retainer weighted toward conversation-rate compounding and Bengali-language flow tuning.",
    }),
    stack: [
      {
        category: "Conversion-first CTAs",
        tools: ["Click-to-call native", "WhatsApp opt-in over email", "Callback-now SLA"],
        cityNote: "10-minute callback promise — daytime SLA enforced; tomorrow-11am evening fallback.",
      },
      {
        category: "Bilingual flows",
        tools: ["Bengali confirmation flows", "Auto-WhatsApp inside 60s", "Bengali SDR routing"],
        cityNote: "Bengali handoff for Bengali-region buyers · Hindi for Marwari/Sindhi traders.",
      },
      {
        category: "Legacy ERP integration",
        tools: ["Tally", "BUSY", "Custom Excel imports"],
        cityNote: "BBD Bagh traders run their own home-rolled stacks — we adapt.",
      },
      {
        category: "Education + finance",
        tools: ["Razorpay", "EMI partners", "Application UX"],
        cityNote: "IIM-C / Jadavpur adjacent — student application + parent UX.",
      },
      {
        category: "Compliance",
        tools: ["DPDP Act", "Bengal-state-specific"],
        cityNote: "DPA signing at trader-floor pace — not ideal but workable.",
      },
    ],
    cadence: [
      { day: "Mon", ritual: "Trader-floor visit", channel: "On-site" },
      { day: "Tue", ritual: "Build sprint", channel: "Slack" },
      { day: "Wed", ritual: "Bengali content QA", channel: "Loom" },
      { day: "Thu", ritual: "Callback-flow review", channel: "Slack" },
      { day: "Fri", ritual: "Friday Loom demo", channel: "Loom + WhatsApp" },
      { day: "Sat", ritual: "On-site stabilisation", channel: "On-site" },
    ],
    proofPoints: [
      { metric: "2x", label: "Inquiry-to-conversation rate" },
      { metric: "60 days", label: "Time to measurable lift" },
      { metric: "−45%", label: "Form-abandon rate after callback-now" },
      { metric: "10 min", label: "Daytime callback SLA" },
    ],
    commercialNotes: [
      "INR + GST · classical TDS 194J posture",
      "Discovery week ₹1.5L–₹3L · field-visit included",
      "Monthly retainers ₹30K–₹80K depending on language ops",
    ],
  },

  /* ============================== AHMEDABAD ============================ */
  ahmedabad: {
    slug: "ahmedabad",
    presenceModel: "hybrid-onsite",
    presenceTagline:
      "Gujarati-first ops · weekly Naroda / Vatva / GIDC visits during cluster engagements.",
    onSiteCadence:
      "Weekly Naroda / Narol / Vatva textile-cluster days · monthly GIFT City / SG Highway syncs",
    leadRole: "Gujarat textile + chemical lead",
    languages: ["Gujarati", "Hindi", "English"],
    hours: "Mon–Sat · 9:30–18:30 IST · WhatsApp-group monitoring 8–22 IST",
    engagement: COMMON_PHASES({
      0: "WhatsApp group seeding audit in week 1 — identify active groups + decision-makers. Tally migration scope locked.",
      1: "Catalog architecture for WhatsApp preview + Gujarati order flow + GST e-invoicing scoped before any code.",
      2: "WhatsApp catalog + Gujarati flow ships first (4–6 weeks). Tally → cloud ERP migration runs in parallel for 60–90 days.",
      3: "Monthly retainer weighted toward catalog-drop scheduling, RFQ flow tuning, and dealer adoption.",
    }),
    stack: [
      {
        category: "WhatsApp commerce",
        tools: ["WhatsApp Business API", "Catalog OG-tuned", "Group-drop scheduling"],
        cityNote: "Catalog seeded into 5–10 trader groups per cluster — no spam.",
      },
      {
        category: "Vernacular flows",
        tools: ["Gujarati order placement", "Gujarati invoice + tracker", "Bilingual confirmation"],
        cityNote: "Gujarati-first UI for shop-floor users · English fallback.",
      },
      {
        category: "Tally migration",
        tools: ["12-month historical import", "Master + opening balance migration", "Daily reconciliation"],
        cityNote: "Tally + cloud ERP run in parallel 60–90 days · CA signs off cut-over.",
      },
      {
        category: "GST e-invoicing",
        tools: ["NIC IRP API", "E-way bill auto-gen", "GSTR exports"],
        cityNote: "IRN at finalisation, e-way bill at dispatch — Vapi/Bharuch tested.",
      },
      {
        category: "Diamonds + GIFT City",
        tools: ["GST + IFSC", "Multi-currency", "Diamond-grade compliance"],
        cityNote: "Surat + Ahmedabad diamond cluster + GIFT City IFSC overlap.",
      },
    ],
    cadence: [
      { day: "Mon", ritual: "WhatsApp catalog drop schedule", channel: "WhatsApp" },
      { day: "Tue", ritual: "Naroda / Vatva site visit", channel: "On-site" },
      { day: "Wed", ritual: "Build sprint", channel: "Slack" },
      { day: "Thu", ritual: "Gujarati QA + Tally reconciliation", channel: "Loom" },
      { day: "Fri", ritual: "Friday Loom demo", channel: "Loom + WhatsApp" },
      { day: "Sat", ritual: "Cluster on-call", channel: "WhatsApp" },
    ],
    proofPoints: [
      { metric: "+180%", label: "Inbound RFQs (90-day, WA-seeded)" },
      { metric: "<5%", label: "Stock divergence post-Tally migration" },
      { metric: "Daily", label: "P&L on founder's phone" },
      { metric: "100%", label: "GST e-invoicing automated" },
    ],
    commercialNotes: [
      "INR + GST · Gujarati-language invoicing optional",
      "Discovery week ₹2L–₹4L · cluster-visit included",
      "Build fixed-price · ongoing ₹50K–₹1.4L/month",
    ],
  },

  /* ============================== JAIPUR =============================== */
  jaipur: {
    slug: "jaipur",
    presenceModel: "site-visit",
    presenceTagline:
      "Heritage-craft engagements run on monthly Sanganer / Bagru / Johari Bazaar visits with the artisan family.",
    onSiteCadence:
      "Monthly Sanganer / Bagru block-print cluster visits · Johari Bazaar gem-trade walks during launches",
    leadRole: "Heritage-craft + export lead",
    languages: ["Hindi", "Marwari", "English"],
    hours: "Mon–Sat · 10–19 IST · 2–3h US-ET / GST-AE overlap for NRI buyers",
    engagement: COMMON_PHASES({
      0: "Cluster + artisan-family inventory in week 1 — block-by-block provenance map. GI-tag schema scoping in parallel.",
      1: "Cluster landing pages + provenance schema + multi-currency NRI checkout architecture scoped before code.",
      2: "Cluster pages (Sanganer / Bagru / Jaipur-jewellery) ship first (3–5 weeks). Schema + NRI checkout + photography direction next.",
      3: "Monthly retainer weighted toward new artisan attribution + NRI Instagram-share optimisation.",
    }),
    stack: [
      {
        category: "Provenance + schema",
        tools: ["Block-by-block artisan attribution", "GI-tag JSON-LD", "Cluster + technique pages"],
        cityNote: "Sanganer GI 86 + Bagru registered designs — schema-tagged.",
      },
      {
        category: "NRI checkout",
        tools: ["USD/GBP/AED/SGD toggle", "Stripe-International", "Razorpay-International"],
        cityNote: "Multi-currency + NRI loan-friendly checkout flows.",
      },
      {
        category: "Storefront",
        tools: ["Shopify + custom Liquid", "Next.js cluster pages", "Photography direction"],
        cityNote: "Shopify checkout + custom-grade content — best of both.",
      },
      {
        category: "Gem trade ops",
        tools: ["GIA / IGI certificate display", "BIS hallmark schema", "Per-stone provenance"],
        cityNote: "Sitapura SEZ-aligned · Johari Bazaar trade pattern respected.",
      },
      {
        category: "Compliance",
        tools: ["DPDP", "Foreign-buyer KYC", "Customs documentation"],
        cityNote: "Export-grade documentation built into the order flow.",
      },
    ],
    cadence: [
      { day: "Mon", ritual: "Sanganer / Bagru cluster visit", channel: "On-site" },
      { day: "Tue", ritual: "Build sprint", channel: "Slack" },
      { day: "Wed", ritual: "Photography + content review", channel: "Loom" },
      { day: "Thu", ritual: "NRI checkout QA", channel: "Slack" },
      { day: "Fri", ritual: "Friday Loom demo", channel: "Loom + Email" },
      { day: "Sat", ritual: "Weekend NRI campaign window", channel: "WhatsApp" },
    ],
    proofPoints: [
      { metric: "+47%", label: "Average order value (provenance rebuild)" },
      { metric: "+31%", label: "NRI repeat-buyer rate" },
      { metric: "8–12 weeks", label: "Provenance rebuild timeline" },
      { metric: "30–50%", label: "Premium captured on traceable pieces" },
    ],
    commercialNotes: [
      "INR + GST · USD invoicing for NRI ops",
      "Discovery week ₹2L–₹3L (cluster-visit included)",
      "Build fixed-price · ongoing ₹40K–₹1L/month",
    ],
  },

  /* ============================== INDORE =============================== */
  indore: {
    slug: "indore",
    presenceModel: "site-visit",
    presenceTagline:
      "Logistics-belt engagements run on monthly Pithampur SEZ + Mhow corridor visits with the operations team.",
    onSiteCadence:
      "Monthly Pithampur SEZ + Mhow corridor visits · quarterly central-Indore (Rajwada / Sarafa) syncs",
    leadRole: "Central-India logistics + manufacturing lead",
    languages: ["Hindi", "Malwi", "English"],
    hours: "Mon–Sat · 10–19 IST · evening dispatch-cover during launches",
    engagement: COMMON_PHASES({
      0: "Carrier + tracker integration audit in week 1. Hindi-first UI scoping for buyers + dispatch teams.",
      1: "Public consignment-lookup widget + Hindi tracker UI + WhatsApp shipment-status flow scoped first.",
      2: "Public tracker + WhatsApp shipment broadcasts ship first (3–4 weeks). Long-tail lane content + dealer portal layer next.",
      3: "Monthly retainer weighted toward lane-page expansion + carrier-integration tuning.",
    }),
    stack: [
      {
        category: "Tracker UI",
        tools: ["Public consignment lookup", "Hindi-first invoice + tracker", "Carrier webhook in"],
        cityNote: "Buyer self-serves before calling — sales-call inbound −38% measured.",
      },
      {
        category: "Carrier integration",
        tools: ["Delhivery", "Ekart", "BlueDart", "Shadowfax", "FedEx"],
        cityNote: "Multi-carrier webhook fan-in — no carrier lock-in.",
      },
      {
        category: "Lane content (SEO)",
        tools: ["Pithampur → JNPT", "Indore → Mundra", "Lane-specific transit schemas"],
        cityNote: "Long-tail lane pages no aggregator covers.",
      },
      {
        category: "Manufacturing (Pithampur)",
        tools: ["Tally / Marg integration", "Dealer portal", "GST e-invoicing"],
        cityNote: "Pune playbook adapted — Pithampur tier-2/3 supplier scale.",
      },
      {
        category: "Communication",
        tools: ["WhatsApp shipment broadcasts", "Hindi confirmation", "Gujarati for export buyers"],
        cityNote: "Gulf re-export buyers get Gujarati/Arabic-friendly tracker UI.",
      },
    ],
    cadence: [
      { day: "Mon", ritual: "Pithampur SEZ visit", channel: "On-site" },
      { day: "Tue", ritual: "Build sprint", channel: "Slack" },
      { day: "Wed", ritual: "Tracker UI Hindi QA", channel: "Loom" },
      { day: "Thu", ritual: "Carrier integration review", channel: "Slack" },
      { day: "Fri", ritual: "Friday Loom demo", channel: "Loom" },
      { day: "Sat", ritual: "Dispatch on-call", channel: "WhatsApp" },
    ],
    proofPoints: [
      { metric: "−38%", label: "Sales-call inbound" },
      { metric: "+95%", label: "Qualified RFQs (post-tracker)" },
      { metric: "60 days", label: "Tracker payback period" },
      { metric: "Hindi-first", label: "UI by default" },
    ],
    commercialNotes: [
      "INR + GST · TDS 194J supported",
      "Discovery week ₹1.5L–₹3L · field-visit included",
      "Build fixed-price · ongoing ₹40K–₹1L/month",
    ],
  },

  /* ============================== BHOPAL =============================== */
  bhopal: {
    slug: "bhopal",
    presenceModel: "site-visit",
    presenceTagline:
      "Government & PSU engagements run on monthly capital visits with bilingual proposal-kit support.",
    onSiteCadence:
      "Monthly Bhopal capital visits · Vidhan Sabha-area + BHEL Bhopal + Mandideep MIDC syncs during empanelment",
    leadRole: "Government / PSU empanelment lead",
    languages: ["Hindi", "English", "Urdu"],
    hours: "Mon–Sat · 10–18 IST · government-procurement-window cover",
    engagement: COMMON_PHASES({
      0: "Capability statement + past-performance grid audit in week 1. GeM / CPPP listing optimisation scoping in parallel.",
      1: "/capability + /past-performance + /compliance site architecture + bilingual proposal-kit scoped first.",
      2: "Capability page + downloadable proposal kit ship first (3–4 weeks). GeM + CPPP listings rebuilt next.",
      3: "Monthly retainer weighted toward new capability statements + RFP response support.",
    }),
    stack: [
      {
        category: "Procurement-ready content",
        tools: ["Capability statement (PDF + HTML)", "Past-performance grid + schema", "Compliance one-pager"],
        cityNote: "/capability outranks the homepage on intent searches.",
      },
      {
        category: "Listings",
        tools: ["GeM seller listing", "CPPP profile", "MSME / NSIC certificate display"],
        cityNote: "Optimised listings rank above incomplete ones on Google.",
      },
      {
        category: "Bilingual outreach",
        tools: ["Hindi cover letters", "English capability decks", "Urdu where relevant"],
        cityNote: "MP-state procurement officers prefer Hindi · central is English-default.",
      },
      {
        category: "Education + research",
        tools: ["IISER / AIIMS Bhopal-aligned", "MANIT / NLIU partnerships"],
        cityNote: "Education-research-board ecosystem overlap.",
      },
      {
        category: "Heritage-tourism (Sanchi)",
        tools: ["Multilingual heritage pages", "Schema for landmarks", "GBP heritage circuit"],
        cityNote: "Bhopal–Sanchi–Pachmarhi heritage circuit content.",
      },
    ],
    cadence: [
      { day: "Mon", ritual: "Capital + Vidhan Sabha-area visit", channel: "On-site" },
      { day: "Tue", ritual: "Capability content sprint", channel: "Slack" },
      { day: "Wed", ritual: "Hindi/English bilingual QA", channel: "Loom" },
      { day: "Thu", ritual: "GeM listing optimisation", channel: "Email + GeM portal" },
      { day: "Fri", ritual: "Friday Loom demo", channel: "Loom + Email" },
    ],
    proofPoints: [
      { metric: "+3x", label: "Empanelment success rate (6 months)" },
      { metric: "+4x", label: "Inbound RFQs from procurement officers" },
      { metric: "4–8 weeks", label: "Initial GeM empanelment cycle" },
      { metric: "Bilingual", label: "Cover letters Hindi-first" },
    ],
    commercialNotes: [
      "INR + GST · GeM-compliant invoicing",
      "Discovery week ₹1.5L–₹2.5L · capital-visit included",
      "Build fixed-price · ongoing ₹30K–₹70K/month",
    ],
  },
};

export function getCityOrganization(slug: string): CityOrganization | undefined {
  return CITY_ORGANIZATION[slug];
}
